[main_panel]
x = 0
y = 0
w = "WINDOW_WIDTH"
h = "WINDOW_HEIGHT"
bg = "BLACK"
border_color = "BLACK"

[label1]
x = 100
y = 100
fg = "WHITE"
font = "montserrat, medium"

[button1]
x = 100
y = 200
w = 150
h = 40
bg = "WHITE"
fg = "BLACK"
font = "montserrat, medium"

[button2]
x = 300
y = 200
w = 150
h = 40
bg = "WHITE"
fg = "BLACK"
font = "montserrat, medium"