[main]
x = 0
y = 0
w = "WINDOW_WIDTH"
h = "WINDOW_HEIGHT"
bg = "WHITE"
border_color = "WHITE"

[label1]
x = 100
y = 100
fg = "BLACK"
font = "montserrat,big"

[button1]
x = 100
y = 200
w = 150
h = 40
bg = "SPANISH_BLUE"
fg = "WHITE"
hov_bg = "GREY"
hov_fg = "BLACK"
font = "montserrat,medium"

[button2]
x = 300
y = 200
w = 150
h = 40
bg = "SPANISH_BLUE"
fg = "WHITE"
hov_bg = "GREY"
hov_fg = "BLACK"
font = "montserrat,medium"

[l1]
x = 100
y = 100
fg = "BLACK"
font = "montserrat,big"

[b1]
x = 200
y = 200
w = 150
h = 40
bg = "SPANISH_BLUE"
fg = "WHITE"
hov_bg = "GREY"
hov_fg = "BLACK"
font = "montserrat,medium"