[main]
x = 0
y = 0
w = "WINDOW_WIDTH"
h = "WINDOW_HEIGHT"
bg = "WHITE"
border_color = "WHITE"

[header]
x = 50
y = 30
fg = "BLACK"
font = "russo,big"

[post1]
x = 50
y = 100
w = 500
h = 150
bg = "SLATE_GREY"
border_color = "CHARCOAL"

[post1_title]
x = 70
y = 120
fg = "WHITE"
font = "montserrat,medium"

[post1_content]
x = 70
y = 150
fg = "WHITE"
font = "montserrat,small"

[read_more1]
x = 400
y = 200
w = 100
h = 30
bg = "SPANISH_BLUE"
fg = "WHITE"
hov_bg = "GREY"
hov_fg = "BLACK"
font = "montserrat,small"

[post2]
x = 50
y = 270
w = 500
h = 150
bg = "SLATE_GREY"
border_color = "CHARCOAL"

[post2_title]
x = 70
y = 290
fg = "WHITE"
font = "montserrat,medium"

[post2_content]
x = 70
y = 320
fg = "WHITE"
font = "montserrat,small"

[read_more2]
x = 400
y = 370
w = 100
h = 30
bg = "SPANISH_BLUE"
fg = "WHITE"
hov_bg = "GREY"
hov_fg = "BLACK"
font = "montserrat,small"

[sidebar]
x = 600
y = 100
w = 400
h = 320
bg = "DIM_GREY"
border_color = "RAISIN_BLACK"

[about_me]
x = 620
y = 120
fg = "WHITE"
font = "russo,medium"

[about_content]
x = 620
y = 150
fg = "WHITE"
font = "montserrat,small"
